#include "RoadSprite.h"


#if defined(GLOBAL_ROAD_WIDTH_IN_SPRITES) && (GLOBAL_ROAD_WIDTH_IN_SPRITES >= 26)

static const RoadSpriteType segmentBasicRoute2[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	{ T_GRASS____, T_GRASS____, T_GCURR2_B1, T_RCURR2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_TREE___C1, T_TREE___C2, T_GCURR2_A1, T_RCURR2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_TREE___E1, T_TREE___E2, T_GRASS____, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR2_B2, T_GCURR2_B2, T_GRASS____, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR2_A2, T_GCURR2_A2, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR2_B1, T_RCURR2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GCURR2_A1, T_RCURR2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_TREE___D1, T_TREE___D2, T_BUSH___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR2_B1, T_RCURR2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GCURR2_A1, T_RCURR2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR2_B2, T_GCURR2_B2, T_GRASS____, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR2_A2, T_GCURR2_A2, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR2_B1, T_RCURR2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GCURR2_A1, T_RCURR2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_TREE___D1, T_TREE___D2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___C1, T_TREE___C2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_LAKE__C01, T_LAKE__C02, T_LAKE__C03, T_LAKE__C04, T_LAKE__C05 },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_LAKE__C06, T_BOAT___A1, T_BOAT___A2, T_WATER____, T_LAKE__C10 },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_LAKE__C11, T_LAKE__C12, T_LAKE__C13, T_LAKE__C14, T_LAKE__C15 },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_HOUSE__B1, T_HOUSE__B2, T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___C1, T_TREE___C2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL2_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_A2, T_GCURL2_A2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____ },

	// Rozszerzenie drogi na dwupasmową
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_C1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR2_A2, T_GCURR2_A2, T_GCURR3_C2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___A1, T_TREE___A2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_BUSH___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A1, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_A2, T_TREE___A1, T_TREE___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_C1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____C1, T_BIF____C_, T_BIF____C2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____F1, T_RCURR3_C2, T_GCURR3_C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____B1, T_BIF____B_, T_BIF____B2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____A1, T_BIF_____A, T_BIF____A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_A2, T_GCURL2_A2, T_RMINUS_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	// Dwie drogi obok siebie
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	// Podwójny most
	{ T_TWATER_B1, T_TWATER_B3, T_TWATER_B3, T_TWATER_B2, T_RAIL___B1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_TWATER_B1, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___B2, T_TWATER_B2, T_TWATER_B4, T_TWATER_B2, T_TWATER_B2, T_TWATER_B4 },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_RAIL___A1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_WATER____, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___A2, T_WATER____, T_WATER____, T_WATER____, T_WATER____, T_WATER____ },
	{ T_TWATER_A4, T_TWATER_A1, T_TWATER_A2, T_TWATER_A2, T_RAIL___C1, T_BRIDGE_A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A2, T_TWATER_A3, T_BRIDGE_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BRIDGE_A1, T_RAIL___C2, T_TWATER_A4, T_TWATER_A1, T_TWATER_A2, T_TWATER_A2, T_TWATER_A1 }, 

	// Zwężenie dróg z dwupasmowej na jednopasmową
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GCURL2_B1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____D1, T_BIF_____B, T_BIF____D2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____E1, T_BIF____E_, T_BIF____E2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_B2, T_GCURL3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_A1, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____F1, T_BIF____F_, T_BIF____F2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_A2, T_GCURL3_A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A2, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_TREE___A1, T_TREE___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___A1, T_TREE___A2, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_A1, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	// Zwężanie drogi 
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___B1, T_GRASS____, T_GMINUS_E1, T_RMINUS_E1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_E2, T_GMINUS_E2, T_TREE___A1, T_TREE___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_TREE___A1, T_TREE___A2, T_GRASS____, T_GRASS____, T_TREE___A1, T_TREE___A2, T_GMINUS_D1, T_RMINUS_D1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_D2, T_GMINUS_D2, T_BUSH___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_BUSH___B1, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GMINUS_C1, T_RMINUS_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_C2, T_GMINUS_C2, T_BUSH___A1, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GMINUS_B1, T_RMINUS_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_B2, T_GMINUS_B2, T_GRASS____, T_BUSH___B1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A1, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GRASS____, T_BUSH___A2, T_BUSH___B2, T_RMINUS_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_A2, T_TREE___A1, T_TREE___A2, T_GRASS____, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____ },

	// Skret w lewo
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_B2, T_GCURL2_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_A2, T_GCURL2_A2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GCURL2_B1, T_RCURL2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_B2, T_GCURL3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL2_A1, T_RCURL2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_A2, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_B2, T_GCURL2_B2, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_A2, T_GCURL2_A2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_B2, T_GCURL2_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_A2, T_GCURL2_A2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_TREE___B1, T_TREE___B2, T_GCURL2_B1, T_RCURL2_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_B2, T_GCURL3_B2, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL2_A1, T_RCURL2_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_A2, T_GRASS____, T_TREE___C1, T_TREE___C2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_TREE___E1, T_TREE___E2, T_GRASS____, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_B2, T_GCURL2_B2, T_GRASS____, T_GRASS____, T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL2_A2, T_GCURL2_A2, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___D1, T_TREE___D2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },

	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_TREE___B1, T_TREE___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_GRASS____, T_TREE___E1, T_TREE___E2, T_GRASS____ },
};

#endif /* defined(GLOBAL_ROAD_WIDTH_IN_SPRITES) && (GLOBAL_ROAD_WIDTH_IN_SPRITES >= 26) */



#if defined(GLOBAL_ROAD_WIDTH_IN_SPRITES) && (GLOBAL_ROAD_WIDTH_IN_SPRITES >= 20)

static const RoadSpriteType segmentRoadWidestMeta[] = {
	{ T_GRASS____, T_GRASS____, T_START___A, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START___B, T_GRASS____ }
};


static const RoadSpriteType segmentRoadWidest[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1 },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1 },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2 },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2 },
};


static const RoadSpriteType segmentRoadWidestClose[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1 },
	{ T_GRASS____, T_GRASS____, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A2, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_B2, T_GCURL3_B2, T_BUSH___B1 },
	{ T_GRASS____, T_GRASS____, T_GCURR3_A1, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_A2, T_GCURL3_A2, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_BUSH___A2, T_GCURR3_C1, T_RCURR3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_C2, T_GCURL3_C2, T_TREE___A1, T_TREE___A2 },
	{ T_GRASS____, T_TREE___A1, T_TREE___A2, T_GCURR3_B1, T_RCURR3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_B2, T_GCURL3_B2, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GCURR3_A1, T_RCURR3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURL3_A2, T_GCURL3_A2, T_BUSH___B1, T_GRASS____ }
};


static const RoadSpriteType segmentRoadWide[] = {
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_GRASS____, T_GRASS____ }
};


static const RoadSpriteType segmentRoadWidestOpen[] = {
	{ T_GRASS____, T_GRASS____, T_GRASS____, T_GCURL3_C1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GCURR3_C2, T_BUSH___A1, T_GRASS____ },
	{ T_GRASS____, T_TREE___A1, T_TREE___A2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_GRASS____, T_GRASS____ },
	{ T_GRASS____, T_GRASS____, T_BUSH___A1, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_TREE___A1, T_TREE___A2 },
	{ T_GRASS____, T_GRASS____, T_GCURL3_C1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GCURR3_C2, T_GRASS____ },
	{ T_GRASS____, T_BUSH___B2, T_GCURL3_B1, T_RCURL3_B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_B2, T_GCURR3_B2, T_BUSH___A2 },
	{ T_GRASS____, T_GRASS____, T_GCURL3_A1, T_RCURL3_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_A2, T_GCURR3_A2, T_GRASS____ },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2 }
};


static const RoadSpriteType segmentRoadWidestBifurcationOpen[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____C1, T_BIF____C_, T_BIF____C2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1 },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____B1, T_BIF____B_, T_BIF____B2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1 },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____A1, T_BIF_____A, T_BIF____A2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2 },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RMINUS_A2, T_GCURL2_A2, T_RMINUS_A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2 },
};


static const RoadSpriteType segmentRoadWidestDoubleMeta[] = {
	{ T_GRASS____, T_GRASS____, T_START___A, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START___B, T_GRASS____, T_START___A, T_START____, T_START____, T_START____, T_START____, T_START____, T_START____, T_START___B, T_GRASS____ }
};


static const RoadSpriteType segmentRoadWidestDouble[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1 },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1 },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2 },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2 },
};


static const RoadSpriteType segmentRoadWidestBifurcationClose[] = {
	{ T_GRASS____, T_BUSH___B1, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RCURR3_C2, T_GCURL2_B1, T_RCURL3_C1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A1 },
	{ T_GRASS____, T_BUSH___A2, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____D1, T_BIF_____B, T_BIF____D2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B1 },
	{ T_GRASS____, T_BUSH___B2, T_RECT___B1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____E1, T_BIF____E_, T_BIF____E2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___B2, T_BUSH___A2 },
	{ T_GRASS____, T_BUSH___A1, T_RECT___A1, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_BIF____F1, T_BIF____F_, T_BIF____F2, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_ROAD_____, T_RECT___A2, T_BUSH___B2 },
};

#endif /* defined(GLOBAL_ROAD_WIDTH_IN_SPRITES) && (GLOBAL_ROAD_WIDTH_IN_SPRITES >= 20) */
